# Experiment 1

In [11]:
import pandas as pd

In [19]:
data = pd.read_csv("train_triplets_sample.txt",header = None
                       ,delimiter=r"\s+")
  
# adding column headings
data.columns = ['User', 'Song', 'Play_Count']
  
# store dataframe into csv file
data.to_csv('train_triplets_sample_updated.csv', 
                index = None)

In [20]:
df=pd.read_csv("train_triplets_sample_updated.csv")

In [21]:
df.head()

                                       User                Song  Play_Count
0  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOAKIMP12A8C130995           1
1  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOAPDEY12A81C210A9           1
2  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBBMDR12A8C13253B           2
3  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBFNSP12AF72A0E22           1
4  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBFOVM12A58A7D494           1

In [30]:
lst=df.values.tolist()
lst.sort()

In [31]:
users=df["User"].tolist()

In [32]:
unique_users=list(set(users))

In [33]:
songs=df["Song"].tolist()
unique_songs=list(set(songs))

In [36]:
unique_users_play_count = []
for i in unique_users:
    x=0
    count=0
    for j in lst:
        if(j[0]==i):
            x=1
            count+=j[2]
        
        elif(j[0]!=i and x==1):
            break
        
    unique_users_play_count.append(count)

In [37]:
unique_users_play_count

[80,
 228,
 125,
 58,
 34,
 78,
 606,
 24,
 164,
 73,
 16,
 95,
 18,
 28,
 105,
 12,
 413,
 135,
 38,
 354,
 41,
 134,
 1422,
 94,
 107,
 208,
 22,
 14,
 39,
 58,
 128,
 120]

In [40]:
unique_songs_play_count = []
for i in unique_songs:
    x=0
    count=0
    for j in lst:
        if(j[1]==i):
            x=1
            count+=j[2]
        
        elif(j[1]!=i and x==1):
            break
        
    unique_songs_play_count.append(count)

In [41]:
unique_songs_play_count

[1,
 1,
 1,
 1,
 8,
 11,
 1,
 8,
 1,
 6,
 1,
 3,
 1,
 1,
 12,
 3,
 1,
 3,
 2,
 1,
 1,
 2,
 1,
 1,
 7,
 7,
 1,
 1,
 1,
 2,
 1,
 4,
 2,
 1,
 1,
 4,
 1,
 3,
 1,
 1,
 1,
 1,
 1,
 23,
 1,
 1,
 3,
 1,
 5,
 5,
 1,
 1,
 1,
 1,
 2,
 5,
 1,
 2,
 1,
 3,
 1,
 5,
 3,
 2,
 2,
 3,
 1,
 2,
 3,
 1,
 5,
 7,
 1,
 1,
 2,
 2,
 1,
 1,
 6,
 6,
 1,
 1,
 2,
 2,
 1,
 1,
 2,
 1,
 7,
 1,
 2,
 1,
 1,
 5,
 1,
 1,
 16,
 1,
 1,
 1,
 1,
 1,
 11,
 1,
 1,
 1,
 3,
 1,
 6,
 1,
 2,
 1,
 5,
 4,
 3,
 1,
 1,
 7,
 3,
 3,
 1,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 5,
 2,
 1,
 1,
 1,
 1,
 2,
 3,
 7,
 4,
 1,
 1,
 1,
 1,
 1,
 3,
 1,
 5,
 1,
 11,
 1,
 11,
 1,
 1,
 2,
 1,
 2,
 1,
 1,
 17,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 6,
 1,
 2,
 7,
 10,
 1,
 1,
 1,
 4,
 2,
 1,
 6,
 2,
 1,
 5,
 1,
 1,
 7,
 6,
 5,
 1,
 5,
 1,
 1,
 1,
 1,
 1,
 2,
 5,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 16,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 6,
 2,
 5,
 1,
 1,
 11,
 1,
 1,
 3,
 1,
 6,
 1,
 1,
 4,
 1,
 2,
 1,
 1,
 1,
 2,
 2,
 1,
 2,
 4,
 1,
 5,
 8,
 1,
 1,
 13,
 1,
 1,
 1,
 5,
 5,
 2,
 1,
 6,
 3,
 1,
 12,
 1,
 1,
 16,
 2,
 5,
 2,
 1,
 6,
 1,
 1,
 2,
 2,
 1,
 2,
 1,
 1,
 4,
 2,
 1,
 1,
 1,
 1,
 7,
 1,
 1,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 5,
 5,
 1,
 8,
 1,
 1,
 3,
 1,
 2,
 1,
 1,
 1,
 4,
 1,
 5,
 2,
 4,
 1,
 4,
 1,
 1,
 2,
 3,
 1,
 1,
 3,
 2,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 13,
 5,
 1,
 1,
 5,
 1,
 7,
 1,
 1,
 1,
 5,
 2,
 9,
 7,
 2,
 1,
 1,
 1,
 3,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 8,
 1,
 10,
 3,
 2,
 5,
 3,
 1,
 1,
 1,
 1,
 11,
 1,
 1,
 1,
 2,
 1,
 1,
 6,
 3,
 2,
 4,
 1,
 7,
 1,
 1,
 1,
 5,
 2,
 1,
 1,
 2,
 1,
 2,
 3,
 1,
 1,
 5,
 18,
 2,
 5,
 3,
 3,
 3,
 1,
 19,
 1,
 2,
 1,
 1,
 1,
 1,
 7,
 1,
 1,
 2,
 1,
 3,
 9,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 3,
 12,
 3,
 5,
 1,
 4,
 6,
 3,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 3,
 2,
 5,
 6,
 1,
 1,
 1,
 2,
 17,
 4,
 1,
 2,
 1,
 5,
 1,
 1,
 1,
 3,
 1,
 5,
 1,
 1,
 6,
 1,
 2,
 2,
 1,
 2,
 3,
 1,
 1,
 1,
 3,
 4,
 7,
 1,
 3,
 3,
 1,
 12,
 1,
 1,
 1,
 2,
 2,
 1,
 2,
 1,
 7,
 3,
 1,
 1,
 1,
 3,
 1,
 1,
 1,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 15,
 3,
 1,
 1,
 1,
 1,
 1,
 10,
 4,
 1,
 5,
 2,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 6,
 1,
 2,
 15,
 1,
 1,
 1,
 1,
 1,
 3,
 1,
 1,
 2,
 1,
 1,
 1,
 2,
 1,
 5,
 1,
 1,
 1,
 1,
 4,
 1,
 1,
 7,
 1,
 2,
 14,
 1,
 1,
 1,
 3,
 1,
 1,
 1,
 1,
 1,
 4,
 1,
 1,
 1,
 1,
 6,
 1,
 2,
 1,
 1,
 2,
 1,
 2,
 6,
 1,
 3,
 7,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 2,
 1,
 6,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 3,
 1,
 1,
 1,
 11,
 4,
 1,
 1,
 2,
 1,
 1,
 2,
 1,
 3,
 2,
 3,
 1,
 2,
 14,
 2,
 1,
 1,
 5,
 5,
 1,
 1,
 1,
 1,
 1,
 10,
 2,
 1,
 12,
 5,
 1,
 17,
 4,
 1,
 1,
 1,
 5,
 1,
 2,
 1,
 8,
 2,
 2,
 1,
 2,
 3,
 2,
 1,
 1,
 4,
 1,
 3,
 3,
 1,
 5,
 8,
 1,
 2,
 3,
 3,
 1,
 7,
 1,
 1,
 1,
 1,
 1,
 9,
 3,
 1,
 5,
 2,
 1,
 1,
 2,
 11,
 1,
 1,
 1,
 2,
 6,
 6,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 3,
 5,
 1,
 1,
 1,
 1,
 3,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 8,
 1,
 1,
 4,
 1,
 5,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 5,
 1,
 1,
 1,
 1,
 1,
 5,
 2,
 2,
 1,
 3,
 5,
 2,
 1,
 5,
 1,
 3,
 1,
 1,
 1,
 1,
 8,
 1,
 1,
 2,
 1,
 1,
 1,
 8,
 1,
 2,
 3,
 4,
 9,
 1,
 1,
 1,
 1,
 1,
 2,
 3,
 5,
 2,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 4,
 1,
 2,
 3,
 2,
 4,
 11,
 1,
 3,
 18,
 3,
 8,
 1,
 2,
 2,
 3,
 1,
 3,
 1,
 4,
 3,
 1,
 6,
 5,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 6,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 2,
 1,
 2,
 2,
 7,
 1,
 1,
 4,
 3,
 15,
 1,
 2,
 2,
 1,
 1,
 1,
 4,
 5,
 1,
 2,
 1,
 2,
 10,
 1,
 3,
 1,
 3,
 1,
 1,
 26,
 1,
 8,
 1,
 1,
 2,
 3,
 2,
 1,
 1,
 1,
 1,
 5,
 6,
 1,
 5,
 1,
 2,
 5,
 2,
 3,
 1,
 1,
 5,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 6,
 2,
 4,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 6,
 1,
 1,
 5,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 7,
 2,
 2,
 11,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 3,
 1,
 1,
 1,
 1,
 2,
 3,
 6,
 5,
 1,
 3,
 2,
 1,
 1,
 3,
 20,
 5,
 1,
 1,
 2,
 5,
 6,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 5,
 1,
 2,
 1,
 5,
 1,
 1,
 1,
 1,
 4,
 2,
 6,
 1,
 1,
 1,
 1,
 2,
 5,
 5,
 1,
 2,
 1,
 1,
 2,
 1,
 ...]

In [48]:
play_count=df["Play_Count"].tolist()
unique_play_count=list(set(play_count))
x=max(unique_play_count)
print(x)

28

In [50]:
final_lst = []

for j in lst:
    if(j[2]==x):
        final_lst.append(j)

In [51]:
final_lst

[['5a905f000fc1ff3df7ca807d57edb608863db05d', 'SOMVTRL12A67AE0921', 28]]

In [52]:
print(len(lst))

2000

In [53]:
print(len(final_lst))

1

In [54]:
# to create final list as a dataframe and save it as a different.csv file

df_final = pd.DataFrame(final_lst, columns = ['User', 'Song', 'Max_Play_Count'])

In [55]:
df_final

,User,Song,Max_Play_Count
0,5a905f000fc1ff3df7ca807d57edb608863db05d,SOMVTRL12A67AE0921,28

In [56]:
df_final.to_csv('Different.csv', 
                index = None)